Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,45 +1,75 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
-
-# For a detailed guide to building and testing with Python, read the docs:
-# https://circleci.com/docs/language-python/ for more details
 version: 2.1
 
-# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
-# See: https://circleci.com/docs/orb-intro/
-orbs:
-  # See the Python orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
-  python: circleci/python@2.1.1
-
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
-jobs:
-  build-and-test:
-    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
+executors:
+  conda-executor:
     docker:
-      # Specify the version you desire here
-      # See:https://circleci.com/developer/images/image/cimg/python
-      - image: cimg/python:3.12
+      - image: continuumio/miniconda3
 
-    # Add steps to the job
-    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
+jobs:
+  build:
+    executor: conda-executor
     steps:
-      # Checkout the code as the first step.
       - checkout
-      - python/install-packages:
-          pkg-manager: pip
-          # app-dir: ~/project/package-directory/  # If your requirements.txt isn't in the root directory.
-          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
       - run:
-          name: Run tests
-          # This assumes pytest is installed via the install-package step above
-          command: pytest
+          name: Install Conda Build and AWS CLI
+          command: conda install conda-build awscli -c conda-forge
+      - run:
+          name: Build Conda Package
+          command: |
+            conda build conda-recipe --output-folder /tmp/conda-bld
+            echo "Listing contents of /tmp/conda-bld:"
+            ls -l /tmp/conda-bld
+      - run:
+          name: Debug Package Directory
+          command: |
+            echo "Listing contents of /tmp/conda-bld/linux-64:"
+            ls -l /tmp/conda-bld/linux-64
+            echo "Listing contents of /tmp/conda-bld/noarch:"
+            ls -l /tmp/conda-bld/noarch
+      - run:
+          name: Upload to Another Git Repo
+          command: |
+           
+            PACKAGE_NAME=$(basename ${PACKAGE_PATH})
+            echo "Found package: ${PACKAGE_NAME}" # Find the package file
+            PACKAGE_PATH=$(find /tmp/conda-bld/linux-64 -name '*.tar.bz2' | head -n 1)
+            
+            if [ -z "$PACKAGE_PATH" ]; then
+              echo "No package file found, aborting."
+              exit 1
+            fi
+            
+            
+            # Clone the repository using HTTPS with a Personal Access Token
+            git clone https://surendra2:${GITHUB_TOKEN}@github.com/surendra2/conda-store.git
+            cd conda-store
+            
+            # Configure Git user
+            git config --global user.email "surendranagula@gmail.com"
+            git config --global user.name "surendra nagula"
+            
+            # Checkout the branch or create it if it doesn't exist
+            git checkout packages || git checkout -b packages
+            
+            # Copy the package to the repo
+            cp ${PACKAGE_PATH} .
+            git add ${PACKAGE_NAME}
+            git commit -m "Add new Conda package ${PACKAGE_NAME}"
+            
+            # Pull and rebase to handle conflicts
+            git pull origin packages --rebase || {
+              echo "Merge conflict encountered. Resolving..."
+              git rebase --abort
+              git pull origin packages --no-rebase
+            }
+            
+            git push origin packages
+      - run:
+          name: Clean up
+          command: conda clean --all --yes
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
 workflows:
-  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
-    # Inside the workflow, you define the jobs you want to run.
+  version: 2
+  build_and_upload:
     jobs:
-      - build-and-test
+      - build
